import { defineField, defineType } from "sanity";

const blank = "Leave blank to keep the current website text.";

function photo(name: string, title: string, group: string, hint?: string) {
  return defineField({
    name,
    title,
    type: "image",
    group,
    description: hint || "Upload to replace the current photo. Leave empty to keep the placeholder.",
    options: { hotspot: true },
    fields: [defineField({ name: "alt", title: "Alt text", type: "string" })],
  });
}

function str(name: string, title: string, opts?: { rows?: number; hint?: string }) {
  if (opts?.rows) {
    return defineField({
      name,
      title,
      type: "text",
      rows: opts.rows,
      description: opts.hint || blank,
    });
  }
  return defineField({
    name,
    title,
    type: "string",
    description: opts?.hint || blank,
  });
}

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  description: "Photos, copy, address and contact. Booking (Glofox) is not edited here.",
  groups: [
    { name: "contact", title: "Identity & contact", default: true },
    { name: "photos", title: "Photos" },
    { name: "home", title: "Homepage" },
    { name: "classesPage", title: "Classes page" },
    { name: "firstVisit", title: "First visit" },
    { name: "pricing", title: "Pricing cards" },
    { name: "teamPage", title: "Team page" },
    { name: "schedulePage", title: "Schedule page" },
    { name: "cta", title: "Footer & banners" },
  ],
  fields: [
    /* ---------- identity & contact ---------- */
    defineField({ name: "name", title: "Studio name", type: "string", group: "contact", description: blank }),
    defineField({ name: "legalName", title: "Legal name", type: "string", group: "contact", description: "Shown in the footer and legal pages." }),
    defineField({ name: "tagline", title: "Tagline", type: "string", group: "contact" }),
    defineField({ name: "logoSub", title: "Logo subline", type: "string", group: "contact", description: "Small line under the wordmark, e.g. pilates studio" }),
    defineField({
      name: "logo",
      title: "Logo image (optional)",
      type: "image",
      group: "contact",
      description: "Replaces the VALERI wordmark in the header. Leave empty to keep the typeface logo.",
      options: { hotspot: true },
    }),
    defineField({
      name: "favicon",
      title: "Favicon (optional)",
      type: "image",
      group: "contact",
      description: "Browser tab icon. PNG or square image works best. Leave empty to keep the default.",
    }),
    defineField({ name: "city", title: "City line", type: "string", group: "contact", description: "e.g. Arjan, Dubai" }),
    defineField({ name: "addressLine1", title: "Address line 1", type: "string", group: "contact" }),
    defineField({ name: "addressLine2", title: "Address line 2", type: "string", group: "contact" }),
    defineField({
      name: "addressShort",
      title: "Short address",
      type: "string",
      group: "contact",
      description: "One line for the footer and header, e.g. Oxford Gardens · Arjan · Dubai",
    }),
    defineField({ name: "hours", title: "Opening hours", type: "string", group: "contact", description: "e.g. Mon–Fri 6:30–21:00 · Sat–Sun 7:00–15:00" }),
    defineField({ name: "whatsapp", title: "WhatsApp number", type: "string", group: "contact", description: "International format, e.g. +971 50 123 4567" }),
    defineField({ name: "phone", title: "Phone number (for the call button)", type: "string", group: "contact", description: "International format. Leave blank to hide the call button." }),
    defineField({ name: "email", title: "Email", type: "string", group: "contact", description: "Also replaces [EMAIL] on legal pages." }),
    defineField({ name: "instagramHandle", title: "Instagram handle", type: "string", group: "contact", description: "With the @, e.g. @valeri" }),
    defineField({ name: "instagramUrl", title: "Instagram URL", type: "url", group: "contact" }),
    defineField({ name: "mapEmbedUrl", title: "Google Maps embed URL", type: "url", group: "contact", description: "The src from Google Maps → Share → Embed a map" }),
    defineField({ name: "seoTitle", title: "Browser / Google title", type: "string", group: "contact", description: blank }),
    defineField({ name: "seoDescription", title: "Browser / Google description", type: "text", rows: 3, group: "contact", description: blank }),
    defineField({ name: "headerCta", title: "Header button", type: "string", group: "contact", description: "Short label, e.g. Book" }),
    defineField({ name: "bookCta", title: "Main booking button", type: "string", group: "contact", description: "e.g. Book your first class" }),

    /* ---------- photos ---------- */
    photo("homeHero", "Homepage hero", "photos"),
    photo("belongPhoto", "“Every body belongs here” photo", "photos"),
    photo("classesHero", "Classes page photo", "photos"),
    photo("studioPhoto", "Studio band (classes page)", "photos"),
    defineField({
      name: "studioGallery",
      title: "Studio gallery (classes page)",
      type: "array",
      group: "photos",
      description: "More photos beside the studio photo. Each keeps its own shape. Leave empty to keep the current set.",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [defineField({ name: "alt", title: "Alt text", type: "string" })],
        },
      ],
    }),
    photo("firstVisitHero", "First Visit page photo", "photos"),
    photo("teamHero", "Team page photo", "photos"),

    /* ---------- homepage copy ---------- */
    defineField({
      name: "home",
      title: "Homepage copy",
      type: "object",
      group: "home",
      fields: [
        str("eyebrow", "Hero eyebrow", { hint: "Leave blank to use “Reformer Pilates in {city}”." }),
        str("headline", "Hero headline", { hint: "Use a new line for a second row." }),
        str("sub", "Hero subline"),
        str("cta", "Hero button"),
        str("belongEyebrow", "Belong — eyebrow"),
        str("belongHeadline", "Belong — headline"),
        str("belongLead1", "Belong — first paragraph", { rows: 4 }),
        str("belongLead2", "Belong — second paragraph", { rows: 4 }),
        str("belongSig", "Belong — signature line"),
        str("classesEyebrow", "Classes — eyebrow"),
        str("classesHeadline", "Classes — headline"),
        str("classesNote", "Classes — note"),
        str("classesHelper", "Classes — helper under the list", { rows: 3 }),
        str("firstEyebrow", "First class — eyebrow"),
        str("firstHeadline", "First class — headline"),
        str("firstLead", "First class — paragraph", { rows: 4 }),
        str("firstVisitLink", "First visit link label"),
        str("firstOfferK", "Offer card — label"),
        str("firstOfferFineprint", "Offer card — fine print"),
        str("firstOfferAlt", "Offer card — intro pack line", { rows: 2 }),
        str("socialHeadline", "Lately — headline"),
        str("socialNote", "Lately — note"),
      ],
    }),

    /* ---------- classes page ---------- */
    defineField({
      name: "classesPage",
      title: "Classes page copy",
      type: "object",
      group: "classesPage",
      fields: [
        str("eyebrow", "Eyebrow"),
        str("headline", "Headline", { hint: "Use a new line for a second row." }),
        str("lead1", "First paragraph", { rows: 4 }),
        str("lead2", "Second paragraph", { rows: 3 }),
        str("facts", "Facts line"),
        str("cta", "Button"),
        str("helper", "Helper under the class cards", { rows: 3 }),
        str("bookingHeadline", "Schedule block — headline"),
        str("bookingLead", "Schedule block — paragraph", { rows: 4 }),
        str("bookingCta", "Schedule block — button"),
      ],
    }),

    /* ---------- first visit ---------- */
    defineField({
      name: "firstVisit",
      title: "First visit copy",
      type: "object",
      group: "firstVisit",
      fields: [
        str("eyebrow", "Eyebrow"),
        str("headline", "Headline"),
        str("lead", "Lead", { rows: 3 }),
        str("cta", "Button"),
        str("stepsEyebrow", "Steps — eyebrow"),
        str("stepsHeadline", "Steps — headline"),
        str("faqEyebrow", "FAQ — eyebrow"),
        str("faqHeadline", "FAQ — headline"),
      ],
    }),
    defineField({
      name: "firstVisitSteps",
      title: "First-visit steps",
      type: "array",
      group: "firstVisit",
      of: [{ type: "visitStep" }],
      description: "Leave empty to keep the current four steps.",
    }),
    defineField({
      name: "faq",
      title: "FAQ",
      type: "array",
      group: "firstVisit",
      of: [{ type: "faqItem" }],
      description: "Leave empty to keep the current questions.",
    }),

    /* ---------- pricing (designed cards until Glofox is connected) ---------- */
    defineField({
      name: "pricingPage",
      title: "Pricing page copy",
      type: "object",
      group: "pricing",
      fields: [
        str("headline", "Headline"),
        str("lead", "Lead"),
        str("facts", "Facts line"),
        str("introLabel", "Intro — label"),
        str("introHeadline", "Intro — headline"),
        str("introNote", "Intro — note", { rows: 3 }),
        str("packsLabel", "Packs — label"),
        str("packsHeadline", "Packs — headline"),
        str("packsNote", "Packs — note", { rows: 3 }),
        str("membersLabel", "Memberships — label"),
        str("membersHeadline", "Memberships — headline"),
        str("membersNote", "Memberships — note", { rows: 4 }),
        str("privateLabel", "Private — label"),
        str("privateHeadline", "Private — headline"),
        str("privateNote", "Private — note", { rows: 3 }),
        str("fineLabel", "Fine print — label"),
        str("fineHeadline", "Fine print — headline"),
        str("termsLink", "Terms link label"),
      ],
    }),
    defineField({
      name: "introOffers",
      title: "Intro offers",
      type: "array",
      group: "pricing",
      of: [{ type: "plan" }],
      description: "Shown until Glofox pricing is connected. Leave empty to keep the current cards.",
    }),
    defineField({
      name: "classPacks",
      title: "Class packs",
      type: "array",
      group: "pricing",
      of: [{ type: "plan" }],
    }),
    defineField({
      name: "memberships",
      title: "Memberships",
      type: "array",
      group: "pricing",
      of: [{ type: "plan" }],
    }),
    defineField({
      name: "privateSessions",
      title: "Private & semi-private",
      type: "array",
      group: "pricing",
      of: [{ type: "plan" }],
    }),
    defineField({
      name: "finePrint",
      title: "Fine print lines",
      type: "array",
      group: "pricing",
      of: [{ type: "string" }],
    }),

    /* ---------- team page copy ---------- */
    defineField({
      name: "teamPage",
      title: "Team page copy",
      type: "object",
      group: "teamPage",
      fields: [
        str("eyebrow", "Eyebrow"),
        str("headline", "Headline"),
        str("lead", "Lead", { rows: 3 }),
        str("instructorsLabel", "Instructors — label"),
        str("instructorsLead", "Instructors — lead"),
        str("storiesLabel", "Stories — label"),
        str("storiesHeadline", "Stories — headline"),
        str("storiesLead", "Stories — lead", { rows: 3 }),
        str("storiesNote", "Stories — note"),
        str("eventsLabel", "Events — label"),
        str("eventsHeadline", "Events — headline"),
        str("eventsLead", "Events — lead", { rows: 3 }),
        str("eventsEmpty", "Events — empty message", { rows: 3 }),
        str("socialLabel", "Social — label"),
        str("socialHeadline", "Social — headline"),
        str("socialNote", "Social — note"),
      ],
    }),

    /* ---------- schedule ---------- */
    defineField({
      name: "schedulePage",
      title: "Schedule page copy",
      type: "object",
      group: "schedulePage",
      fields: [
        str("headline", "Headline"),
        str("lead", "Lead", { rows: 3 }),
        str("notesLabel", "Notes — label"),
        str("notesHeadline", "Notes — headline"),
        str("findUsHeadline", "Find us — headline"),
      ],
    }),
    defineField({
      name: "scheduleNotes",
      title: "Before you book — notes",
      type: "array",
      group: "schedulePage",
      of: [{ type: "scheduleNote" }],
      description: "Leave empty to keep the current bullets.",
    }),

    /* ---------- footer, CTA, legal meta ---------- */
    defineField({
      name: "footerTagline",
      title: "Footer tagline",
      type: "string",
      group: "cta",
      description: blank,
    }),
    defineField({ name: "copyrightYear", title: "Copyright year", type: "string", group: "cta" }),
    defineField({
      name: "showFooterNote",
      title: "Show the footer prototype note",
      type: "boolean",
      group: "cta",
      initialValue: true,
      description: "Turn off when real photos are live.",
    }),
    defineField({
      name: "footerNote",
      title: "Footer prototype note",
      type: "string",
      group: "cta",
      description: "Default: Prototype — imagery is placeholder.",
    }),
    defineField({
      name: "band",
      title: "“New to VALERI” banner",
      type: "object",
      group: "cta",
      fields: [
        str("k", "Label"),
        str("v", "Headline"),
        str("sm", "Fine print"),
        str("cta", "Button"),
      ],
    }),
    defineField({
      name: "cta",
      title: "Bottom call-to-action",
      type: "object",
      group: "cta",
      fields: [
        str("headline", "Headline"),
        str("button", "Button"),
        str("fine", "Fine print"),
      ],
    }),
    defineField({
      name: "legalLastUpdated",
      title: "Legal — last updated",
      type: "date",
      group: "cta",
      description: "Replaces [DATE] on Terms and Privacy. Each legal page can override this.",
    }),
    defineField({
      name: "legalDraft",
      title: "Legal — show draft note",
      type: "boolean",
      group: "cta",
      initialValue: true,
    }),
    defineField({
      name: "legalDraftNote",
      title: "Legal — draft note text",
      type: "string",
      group: "cta",
    }),
  ],
  preview: { prepare: () => ({ title: "Site settings" }) },
});
